<?php

/**
 * @file
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_views_data_alter().
 */
function html_title_views_data_alter(&$data) {
  $data['node_field_data']['title']['field']['id'] = 'node_html_title';
}

/**
 * Implementation of hook_preprocess_page_title()
 */
function html_title_preprocess_page_title(&$variables) {
  if ($node = \Drupal::routeMatch()->getParameter('node')) {
    $variables['node'] = $node;
    $node = $variables['node'];
    $variables['title'] = \Drupal::service('html_title.filter')
      ->decodeToMarkup($node->getTitle());
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function html_title_preprocess_breadcrumb(&$vars) {
  $last = &$vars['breadcrumb'][count($vars['breadcrumb']) - 1];
  if (!isset($last['url'])) {
    $last['text'] = \Drupal::service('html_title.filter')->decodeToMarkup($last['text']);
  }
}

/**
 * Implements hook_block_view_alter().
 */
function html_title_block_view_alter(array &$build, \Drupal\Core\Block\BlockPluginInterface $block) {
  $configuration = $block->getConfiguration();
  $label = !empty($configuration['label_display']) ? $configuration['label'] : '';
  if ($label) {
    // Unfortunately, due to the way \Drupal\block\BlockViewBuilder::preRender
    // works, the "content" doesn't get set until after that method is ran.
    // This method also unsets the #block property which means the raw block
    // title has to be extracted here now. Use #context to pass this along
    // and then set the content title to it.
    $build['#context']['html_title'] = \Drupal::service('html_title.filter')->decodeToMarkup($label);
    $build['#pre_render'][] = 'html_title_block_pre_render';
  }
}

/**
 * Callback for pre-rendering a block.
 *
 * @param array $element
 *   The render array.
 *
 * @return array
 *   The modified render array.
 */
function html_title_block_pre_render(array $element) {
  // Block labels can be dynamically altered, see template_preprocess_block().
  $element['content']['#title'] = $element['#context']['html_title'];
  return $element;
}

/**
 * Implements hook_theme_registry_alter().
 */
function html_title_theme_registry_alter(&$theme_registry) {
  if (isset($theme_registry['breadcrumb'])) {
    $hooks = $theme_registry['breadcrumb']['preprocess functions'];
    if (($pos = array_search('html_title_preprocess_breadcrumb', $hooks)) !== FALSE) {
      unset($hooks[$pos]);
    }
    $hooks[] = 'html_title_preprocess_breadcrumb';

    $theme_registry['breadcrumb']['preprocess functions'] = array_values($hooks);
  }
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function html_title_node_view(array &$build, EntityInterface $node, EntityViewDisplayInterface $display, $view_mode) {
  switch ($view_mode) {
    case 'rss':
      $node->title->value = strip_tags($node->title->value);
      break;

    default:
      $build['title'][0]['#context']['value'] = \Drupal::service('html_title.filter')->decodeToMarkup($build['title'][0]['#context']['value']);
  }
}
